#Deployment
###controllers/pb-deploy.tml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-application-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
  minReadySeconds: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ecommerce-application
  template:
    metadata:
      labels:
        app: ecommerce-application
    spec:
      containers:
      - name: ecommerce-application-container
        image: kavyapallamreddy/ecommerce_application:2
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '1'
            memory: '500Mi'
          requests:
            cpu: '1'
            memory: '500Mi'
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: regcred



