# Service - LoadBalancer
# # pb-service -lb.yml
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-application-service
  labels:
    app: ecommerce-application
spec:
  selector:
    app: ecommerce-applications
  type: NodePort
  ports:
  - nodePort: 31285
    port: 8000
    targetPort: 8000
